#pragma once

#define ID_ADDON_INFO                   32000
#define ID_ADDON_INFO_NAME                  1
#define ID_ADDON_INFO_DESC                  2

#define ID_ADDON_MENU                   32001
#define ID_ADDON_MENU_ABOUT                 1

#define ID_ADDON_MENU_FOR_PALETTE       32002
#define ID_ADDON_MENU_PALETTE               1

#define ID_ADDON_MENU_FOR_UPDATE        32003
#define ID_ADDON_MENU_UPDATE                1

#define ID_PALETTE_STRINGS              32010
#define ID_PALETTE_STRINGS_SELECT_SCRIPTS_TITLE  1
#define ID_PALETTE_STRINGS_SELECT_SCRIPTS_BUTTON 2

#define ID_AUTOUPDATE_STRINGS           32011
#define ID_AUTOUPDATE_NEWVERSION_ALERT_TITLE 1
#define ID_AUTOUPDATE_NEWVERSION_ALERT_TEXT1 2
#define ID_AUTOUPDATE_NEWVERSION_ALERT_TEXT2 3
#define ID_AUTOUPDATE_NEWVERSION_ALERT_BUTTON1 4
#define ID_AUTOUPDATE_NEWVERSION_ALERT_BUTTON2 5
#define ID_AUTOUPDATE_LATESTVERSION_ALERT_TITLE  6
#define ID_AUTOUPDATE_LATESTVERSION_ALERT_TEXT   7
#define ID_AUTOUPDATE_LATESTVERSION_ALERT_BUTTON 8

#define ID_BUILTINSCRIPTS_NAMES         32004

#define ID_TAPIR_LOGO                   32502
#define ID_TAPIR_LOGO_MINI              32503
#define ID_RUN_BUTTON_ICON              32504
#define ID_KILL_BUTTON_ICON             32505
#define ID_OPENSCRIPT_BUTTON_ICON       32506
#define ID_ADDSCRIPT_BUTTON_ICON        32507
#define ID_DELSCRIPT_BUTTON_ICON        32508
#define ID_RUNWITHUPDATE_BUTTON_ICON    32509
#define ID_UPDATE_ICON                  32510

#define ID_ABOUT_DIALOG                 32003
#define ID_PALETTE                      32004

#define ID_COMMON_SCHEMA_DEFINITIONS_FILE 32001
#define ID_ACLIB_INIT_PY_FILE             32000