#ifndef DGTEST_RESIDS_HPP
#define DGTEST_RESIDS_HPP

#define DGTEST_ABOUT_STRINGSID		32000
#define DGTEST_MENU_STRINGSID		32500
#define DGTEST_PROMPT_STRINGSID		32520
#define DGTEST_FONTPOPUPDIALOG_RESID	32650
#define DGTEST_SPLITBUTTONDIALOG_RESID	32651
#define DGTEST_OWNERDRAWNLISTBOXPLT_RESID	12580

#endif // DGTEST_RESIDS_HPP
